suite: Configmap tests
templates:
  - templates/configmap.yaml
tests:
  - it: should fail if https is enabled but no certificate is specified
    set:
      server:
        https:
          enabled: true
          key: /etc/ssl/ssl.key
    asserts:
      - failedTemplate:
          errorPattern: ".*certificate must be specified.*"
  - it: should fail if https is enabled but no key is specified
    set:
      server:
        https:
          enabled: true
          certificate: /etc/ssl/ssl.crt
    asserts:
      - failedTemplate:
          errorPattern: ".*key must be specified.*"
  - it: should fail for invalid log level values
    set:
      server:
        logging:
          serviceLogLevel: INVALID
    asserts:
      - failedTemplate:
          errorPattern: ".*serviceLogLevel must match pattern.*"
  - it: should fail for invalid log level values
    set:
      server:
        logging:
          serviceLogFormat: INVALID
    asserts:
      - failedTemplate:
          errorPattern: ".*serviceLogFormat must match pattern.*"
  - it: should fail if both local and S3 storage are disabled
    set:
      server:
        storage:
          local:
            enabled: false
          s3:
            enabled: false
    asserts:
      - failedTemplate:
          errorPattern: ".*at least one of local or S3 storage must be enabled.*"
  - it: should fail if S3 is enabled but no bucket is specified
    set:
      server:
        storage:
          s3:
            enabled: true
    asserts:
      - failedTemplate:
          errorPattern: ".*bucket must be specified when S3 storage is enabled.*"
